# Generated by Django 3.0.3 on 2020-02-06 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=128, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Last Name')),
                ('profile_picture', models.ImageField(blank=True, upload_to=users.models.get_image_path)),
                ('i_can', models.CharField(max_length=200)),
                ('i_need', models.CharField(max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
